# Generated by Django 2.0.13 on 2019-05-26 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DomainName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='machineName',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='QRInfo',
            fields=[
                ('url', models.URLField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ScanInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected', models.NullBooleanField()),
                ('result', models.CharField(max_length=100)),
                ('machineName', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='machineName', to='app.machineName')),
            ],
        ),
        migrations.CreateModel(
            name='ScreenshotInfo',
            fields=[
                ('qrInfo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='scrInfo', serialize=False, to='app.QRInfo')),
                ('imgPath', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='VirusTotalInfo',
            fields=[
                ('qrInfo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='virusInfo', serialize=False, to='app.QRInfo')),
                ('scanDate', models.DateTimeField()),
                ('positives', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WhoisInfo',
            fields=[
                ('qrInfo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='whoisInfo', serialize=False, to='app.QRInfo')),
                ('registrar', models.TextField(null=True)),
                ('emails', models.EmailField(max_length=254)),
                ('org', models.TextField(null=True)),
                ('address', models.TextField()),
                ('city', models.TextField()),
                ('country', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='scaninfo',
            name='vInfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scanResult', to='app.VirusTotalInfo'),
        ),
        migrations.AddField(
            model_name='domainname',
            name='wInfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domainName', to='app.WhoisInfo'),
        ),
    ]
