# Generated by Django 2.0.13 on 2019-05-26 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='whoisinfo',
            name='emails',
        ),
        migrations.AddField(
            model_name='emailinfo',
            name='wInfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email', to='app.WhoisInfo'),
        ),
    ]
