# Generated by Django 2.0.13 on 2019-05-26 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190526_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainname',
            name='wInfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domainNames', to='app.WhoisInfo'),
        ),
        migrations.AlterField(
            model_name='emailinfo',
            name='wInfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='app.WhoisInfo'),
        ),
    ]
