# Generated by Django 2.0.13 on 2019-05-30 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190526_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whoisinfo',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='whoisinfo',
            name='city',
            field=models.TextField(null=True),
        ),
    ]
