# Generated by Django 2.0.13 on 2019-05-30 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190530_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailinfo',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
